version: "3.8"

services:
  app:
    # Si ya has construido la imagen, puedes usar:
    image: mi-proyecto:latest

    # —O— en lugar de usar la imagen, dejar que Compose la construya:
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "${PORT}:${PORT}"

    # (opcional) si necesitas montar volumenes:
    # volumes:
    #   - ./:/app

    # (opcional) comando de arranque (si no está en el Dockerfile):
    # command: npm start
